name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: [10, 12, 14]
    name: Test ${{ matrix.os }} node${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm test
      - uses: actions/upload-artifact@master
        with:
          name: integration-test-png-cache
          path: integration_tests/bundles/images/.png-cache

  publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - if: github.event_name != 'push' || !startsWith(github.event.ref, 'refs/tags')
        run: npm publish --dry-run
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
