name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            node_version: 24
            metro_version: ^0.83.1
          - os: windows-latest
            node_version: 24
            metro_version: ^0.83.1
          # React Native 0.81-0.83
          - os: ubuntu-latest
            node_version: 24
            metro_version: ^0.83.1
          # React Native 0.79-0.80
          - os: ubuntu-latest
            node_version: 22
            metro_version: ^0.82.0
          # React Native 0.77-0.78
          - os: ubuntu-latest
            node_version: 20
            metro_version: ^0.81.0
    name: Test ${{ matrix.os }} node${{ matrix.node_version }} metro${{ matrix.metro_version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm install --dev --no-save metro@${{ matrix.metro_version }}
      - run: npm test
      - uses: actions/upload-artifact@v5
        with:
          name: integration-test-png-cache-${{ matrix.os }}-node${{ matrix.node_version }}-metro${{ matrix.metro_version }}
          path: integration_tests/bundles/images/.png-cache/
          include-hidden-files: true

  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - expo_version: ~54.0.23
            expo_metro_config_version: ~54.0.2
            react_native_version: 0.81.5
            react_version: 19.1.0
          - expo_version: ~53.0.0
            expo_metro_config_version: 0.20.17
            react_native_version: 0.79.6
            react_version: 19.0.0
          - expo_version: ~52.0.0
            expo_metro_config_version: 0.19.12
            react_native_version: 0.76.9
            react_version: 18.3.1
    name: Example (Expo ${{ matrix.expo_version }})
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            example/package-lock.json
      - run: npm ci
      - run: >
          npm install --dev --no-save
          expo@${{ matrix.expo_version }}
          @expo/metro-config@${{ matrix.expo_version }}
          react-native@${{ matrix.react_native_version }}
          react@${{ matrix.react_version }}
        working-directory: ./example/
      - run: npx install-local
        working-directory: ./example/
      - run: npx expo export
        working-directory: ./example/

  publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - if: github.event_name != 'push' || !startsWith(github.event.ref, 'refs/tags')
        run: npm publish --dry-run
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
